### ISSUE TITLE
Custom jsduck path

### ISSUE THREAD

**Issue by 108adams** [rwhogg/jsduck-from-js#13]
Please add an option to pass a custom path for binary. We have an environment with jsduck.exe not in PATH, hence we cannot find it with _which_

**Comment by bw-yuhogg** [comment]
Hi! Thanks for submitting this issue.

I'll try and release a new version which will allow a custom path out in the near future.

Just a few things:
1. Is it actually called `jsduck.exe`?
2. Related to the first point, are you running this on a Windows machine? If so, while I'll try my best to get it to work, I can't make any promises.
3. Do you like the fact that the installation script installs the `jsduck` gem automatically? Your answer on this will determine if I make this fix against the 0.2.x branch (which does so) or the soon-to-be-released 1.0.x branch (which will not).
4. While I'm happy to assist with this issue, my company is planning on moving away from JSDuck and towards JSDoc, which means that this module is not going to be supported after it's no longer needed by them. See #14 . I would recommend you switch to JSDoc too, as development activity on JSDuck is not great.

Thanks once again!

**Comment by 108adams** [comment]
1. yes, but just allow passing a path, like _path.resolve("a", "path", "to", "jsduck.exe")_
2. if you use _path_ the platform doesn't matter
3. no, I don't like this :) Actually I use statically built jsduck.exe, no ruby installation at all
4. I have already developed a custom handler for jsDuck based on your code, thanks for the starting platform. As for me jsDoc is not an option, at least not now. Thanks anyway.

**Comment by bw-yuhogg** [comment]
I've published version 1.1.0. You can use it like this:

``` javascript
var jsduck = new JSDuck(["--out", "doc"], path.resolve("/", "path", "to", "jsduck"));
```

Closing this for now, but feel free to reopen if you have any problems with it.

Thanks once again!

**Comment by 108adams** [comment]
Thanks for your work and feedback :) Please update README.md to announce the change.

Yours
Adam

**Comment by bw-yuhogg** [comment]
I've updated the GitHub repo, will release a new version so it shows up on npm in a day or two (a little bit busy these days).

**Comment by bw-yuhogg** [comment]
Done. Sorry, I've been _really_ busy recently.
